spring:
  servlet:
    multipart:
      enabled: true
  application:
    name: Image-API
  datasource:
    url: jdbc:postgresql://localhost:5432/ImageAPI
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  web:
    resources:
      static-locations: file:uploads/